### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly#7772]
This is part of the [monorepo project](https://github.com/google/blockly/issues/7755).

- Update docs about how to contribute to plugins
- Update references to develop/master branch in core
- Add documentation  about how version numbers for plugins work
- Add documentation about how to configure dependabot to always update blockly + plugins together
- Update READMEs where needed
  - Audit all links in plugin READMEs (can happen in parallel)

**Comment by jult** [comment]
And updating hints? Most users will have it installed and there's nothing on how to update to newer versions without having to re-install from a new git rebase/clone source.

**Comment by lizschwab** [comment]
For `Add documentation about how to configure dependabot to always update blockly + plugins together` item, we can use the pattern we applied for docusaurus, which looks like this:

```
    groups:
      docusaurus:
        patterns:
          - '@docusaurus/*'
```

See documentation here:
https://docs.github.com/en/code-security/tutorials/secure-your-dependencies/optimizing-pr-creation-version-updates#grouping-related-dependencies-together

**Comment by lizschwab** [comment]
A better description of how to group blockly's dependabot updates together (feel free to re-word):

In your project's `dependabot.yml` file, you can group Blockly and its plugins together using Dependabot's `groups` option. For example, your yml might look something like the following:

```yml
updates:
  - package-ecosystem: 'npm' 
    directory: '/' 
    target-branch: 'main'
    schedule:
      interval: 'weekly'
```
You can configure `groups` to group updates to Blockly and its plugins together like so:
```yml
updates:
  - package-ecosystem: 'npm' 
    directory: '/' 
    target-branch: 'main'
    schedule:
      interval: 'weekly'
    groups:
      blockly: # You can give this a different name if you like
        patterns:
          - 'blockly'
          - '@blockly/*'
```
