### ISSUE TITLE
Add focus outline for flyout labels / buttons

### ISSUE THREAD

**Issue by microbit-robert** [RaspberryPiFoundation/blockly#9140]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

Flyout labels and buttons currently get the default browser focus-visible outline rather than the 'theme outline' shown for blocks.

[This CSS](https://github.com/microsoft/pxt/blob/master/theme/blockly-core.less#L473-L490) can be used to the style these labels and buttons, however, DOM changes could make this CSS simpler. The complexity is due to not being able to draw outlines on SVG group elements in Safari.

```css
/* Flyout buttons and labels */
.blocklyKeyboardNavigation .blocklyFlyout .blocklyFlyoutLabel.blocklyActiveFocus,
.blocklyKeyboardNavigation .blocklyFlyout .blocklyFlyoutButton.blocklyActiveFocus {
    outline: none;
}
/* Use the backgrounds because the group can't have an outline on Safari */
.blocklyKeyboardNavigation .blocklyFlyout .blocklyFlyoutLabel.blocklyActiveFocus > .blocklyFlyoutLabelBackground,
.blocklyKeyboardNavigation .blocklyFlyout .blocklyFlyoutButton.blocklyActiveFocus > .blocklyFlyoutButtonBackground {
    outline-offset: 2px;
    outline: var(--blockly-selection-width) solid
        var(--blockly-active-node-color);
    border-radius: 2px;
}
.blocklyKeyboardNavigation .blocklyFlyout .blocklyFlyoutLabel.blocklyActiveFocus > .blocklyFlyoutLabelBackground {
    // Swap opactity for transparent fill so we can see the focus indicator.
    opacity: 1;
    fill: transparent;
}
```

### Reproduction steps

1. Open https://google.github.io/blockly-keyboard-experimentation/
2. Navigate to the "Misc" -> "A subcategory" item
3. Move focus to the flyout and select the flyout label
4. Observe the focus outline

### Stack trace

```shell

```

### Screenshots

<img width="220" alt="Image" src="https://github.com/user-attachments/assets/118a31a3-5f60-4b76-b8d2-5fef88871636" />
